/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Controller.Utilidades;
import Controller.Utilidadescas;
import Modelos_de_Tablas.Casa;
import Modelos_de_Tablas.Tabla_Casas;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Zumba
 */
public class FrmCasas extends javax.swing.JDialog {
Utilidades u = new Utilidades();
    Utilidadescas uc=new Utilidadescas();
    Tabla_Casas tl = new Tabla_Casas();
    double porcentaje;
    private DefaultTableModel modeloTablaCasas; // Declaración como campo
    private JTable tablaCasas;
    /**
     * Creates new form FrmCasas
     */
    public FrmCasas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         String[] columnas = {"Nº", "Dimensiones y Pisos", "Homónimas"};
    modeloTablaCasas = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        @Override
        public void addRow(Object[] rowData) {
            if (getRowCount() >= 10) {
                removeRow(0);
            }
            super.addRow(rowData);
        }
    };   
    tablaCasas = new JTable(modeloTablaCasas);
    tablaCasas.setRowHeight(20);
    javax.swing.JScrollPane scrollPaneCasas = new javax.swing.JScrollPane(tablaCasas);
    scrollPaneCasas.setBounds(600, 180, 250, 150);
    .add(scrollPaneCasas);
    //10, 40, 600, 400
    // Ajustar jPanel2 a layout absoluto y tamaño
    jPanel2.setLayout(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tabla de Registro de las Casas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 30, 350, 30);

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 60, 110, 30);

        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 452, 402);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 110, 770, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 650);

        setSize(new java.awt.Dimension(879, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Casa nuevaCasa = new Casa(Val, Val); 
        uc.guardarCasa(nuevaCasa);
        // guarda la casa generada (probablemente en una estructura interna, 
        int grupo = uc.getGrupoHomonimas(uc.getContador() - 1);        
        modeloTablaCasas.addRow(new Object[]{uc.getContador(), nuevaCasa.toString(), grupo});
        Datos.guardarDato(uc.getContador(), nuevaCasa.toString(), grupo);
        //guardando las casas en una estructura interna (como un arreglo) para comparaciones de homonimias.
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCasas dialog = new FrmCasas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
